services:
  app:
    build:
      dockerfile: Dockerfile
    image: donghub/qwen:latest
    container_name: qwen-model
    ports:
      - "8080:8080"
    environment:
      - BASE_URL=http://host.docker.internal:11434