services:
  app:
    build:
      dockerfile: Dockerfile
    image: donghub/qwen:latest
    container_name: qwen-model
    ports:
      - "8080:8080"
    environment:
      - BASE_URL=http://host.docker.internal:11434
  postgres:
    image: pgvector/pgvector:pg16
    container_name: pgvector
    environment:
      POSTGRES_DB: ragdb
      POSTGRES_USER: dongho
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dongho -d ragdb" ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  pgvector_data:
    driver: local