spring:
  application:
    name: spring-ai-demo

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
      file-size-threshold: 2MB

  ai:
    ollama:
      base-url: ${BASE_URL:http://localhost:11434}
      chat:
        options:
          model: qwen3-coder:30b
          temperature: 0.7
          num-ctx: 32768

server:
  port: 8080
